# server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 2 # Valor inicial, será alterado pelo script
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: kapelinsky/tcp-server:latest # Sua imagem Docker Hub
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server # Garante que o Service aponte para os pods com este label
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # Para comunicação interna dentro do cluster