# client-job.yaml (Updated to support new env vars)
apiVersion: batch/v1
kind: Job
metadata:
  name: client-job-template 
spec:
  backoffLimit: 0 # Não tente novamente em caso de falha do pod
  template:
    metadata:
      labels:
        app: client
    spec:
      restartPolicy: Never
      containers:
      - name: client
        image: kapelinsky/tcp-client:latest 
        env:
        - name: SERVER_IP
          value: "server-service" # Nome do serviço Kubernetes do servidor
        - name: SERVER_PORT
          value: "8080"
        - name: CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name # Usa o nome do pod como ID do cliente
        - name: NUM_MESSAGES_PER_CLIENT # NEW
          value: "1" # This will be templated by run_tests.sh
        - name: NUM_CONCURRENT_CLIENTS # NEW
          value: "1" # This will be templated by run_tests.sh